### ISSUE TITLE
Compilation fails under node 4.2

### ISSUE THREAD

**Issue by febeling** [eHealthAfrica/grunt-tx#7]
The cause is a dependency on keytar 2.1.0, which fails to build with node 4.2.

**Comment by rmehner** [comment]
Thanks for the report, on it, unfortunately not that easy, because compiler woes on Travis (works fine locally).

**Comment by rmehner** [comment]
Fixed in ba0a5130f6c6ab0a3c57ec3c0eb50811da0f2674, but for some reason semantic-release didn't run. Will update this tomorrow :)

**Comment by rmehner** [comment]
Version 1.1.4 now supports Node 4.x & Node 5.x

**Comment by febeling** [comment]
:sparkles:  Thanks @rmehner! :sparkles:
